services:
  # Nginx
  web:
    user: "1000:1000"
    volumes:
      - ./web/conf/default.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

  # React
  frontend:
    user: "1000:1000"

  # Laravel
  backend:
    user: "1000:1000"
