version: "3"

dotenv:
  - .env

tasks:
  up:
    desc: コンテナを起動
    silent: false
    cmds:
      # .env の環境変数名「UID・GID」を削除
      - sed -i '/^UID=/d' .env 2>/dev/null || true
      - sed -i '/^GID=/d' .env 2>/dev/null || true
      # .env の環境変数名「UID・GID」を追加
      - echo "UID=$(id -u)" >> .env
      - echo "GID=$(id -g)" >> .env
      # コンテナを起動
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose --profile {{if eq .APP_ENV "production"}}prod{{else}}dev{{end}} up -d --build'

  down:
    desc: コンテナを停止
    silent: false
    cmds:
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose --profile {{if eq .APP_ENV "production"}}prod{{else}}dev{{end}} down'

  frontend-build:
    desc: React をビルド
    silent: false
    cmds:
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec frontend npm run build'

  frontend-dev:
    desc: React を開発モードで起動
    silent: false
    cmds:
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec frontend npm run dev'

  db-reset:
    desc: DBを初期化
    silent: false
    cmds:
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend php artisan migrate:fresh --seed'

  cache-clear:
    desc: キャッシュクリア
    silent: false
    cmds:
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend php artisan config:clear'
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend php artisan route:clear'
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend php artisan cache:clear'
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend php artisan view:clear'

  setup:
    desc: すべての環境を構築
    silent: false
    cmds:
      # .env の環境変数名「UID・GID」を削除
      - sed -i '/^UID=/d' .env 2>/dev/null || true
      - sed -i '/^GID=/d' .env 2>/dev/null || true
      # .env の環境変数名「UID・GID」を追加
      - echo "UID=$(id -u)" >> .env
      - echo "GID=$(id -g)" >> .env
      # イメージを再作成し、コンテナを起動
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose --profile {{if eq .APP_ENV "production"}}prod{{else}}dev{{end}} up -d --build'
      # Laravelに、vendorを追加
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend composer install'
      # Laravelに、envファイルを追加
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec backend cp .env.example .env'
      # Reactに、node_module 追加
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec frontend npm install'
      # 静的コンテンツを生成
      - '{{if eq .APP_ENV "production"}}sudo {{end}}docker compose exec frontend npm run build'
      # プロジェクトの所有者を自分に変更する
      - sudo chown -R $(whoami):$(id -gn) .
